config/routes.rb
Rails.application.routes.draw do
  root to: 'certificates#index'
  get 'search', to: 'certificates#search', as: :search_events
  get 'show/:event_id/:participant_id', to: 'certificates#show', as: :show_certificate
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name

  has_and_belongs_to_many :participants, autosave: true

  default_scope { order(created_at: :desc) }

  validates_presence_of :name
  validates_presence_of :location
  validates_presence_of :start_date
  validates_presence_of :end_date
  validates_presence_of :workload
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name
  
  has_and_belongs_to_many :events, autosave: true

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :participation_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  def index
  end

  def search
    @participant = Participant.find_by(email: params[:email])
    render action: :index, alert: "Nenhum participante encontrado com o e-mail \"#{params[:email]}\"", status: :not_found if @participant.nil?
    @events = @participant.events unless @participant.nil?
  end

  def show
    #TODO: Improve error handling if participant is not on a particular event
    #TODO: Test above case
    @event = Event.find(params[:event_id])
    @participant = @event.participants.find(params[:participant_id])
    respond_to do |format|
      format.pdf do
        render pdf:                            "#{@event.name} - #{@participant.name}",
               disposition:                    'attachment',                 # default 'inline'
               template:                       "certificates/#{@event.pdf_template}.pdf.erb",
               layout:                         "#{@event.pdf_layout}.html",                   # use 'pdf.html' for a pdf.html.erb file
               show_as_html:                   params[:debug].present?,      # allow debugging based on url param
               orientation:                    'Landscape',                  # default Portrait
               page_size:                      'Letter',            # default A4
               margin:  {
                  top:               5,
                  bottom:            0,
                  left:              0,
                  right:             0
              },
              title:                          "Certificado #{@event.name}"            # otherwise first page title is used
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-danger",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        # concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
        end
      )
    end
    nil
  end
end

app/views/certificates/2014.pdf.erb
<%=wicked_pdf_image_tag "2014/background.jpg"%>
<h3>Certificamos que <%=@participant.name%> participou como <%=@participant.participation_type%> do(a) <%=@event.name%> em <%=@event.location%>, durante o período de <%=@event.start_date.strftime('%d/%m/%Y')%> à <%=@event.end_date.strftime('%d/%m/%Y')%>, com carga horária de <%=@event.workload%> hora(s).</h3>

app/views/certificates/2015.pdf.erb
<%=wicked_pdf_image_tag "2015/background.jpg"%>
<h3 class="center">Certificamos que <%=@participant.name%> participou como <%=@participant.participation_type%> do(a) <%=@event.name%> em <%=@event.location%>, durante o período de <%=@event.start_date.strftime('%d/%m/%Y')%> à <%=@event.end_date.strftime('%d/%m/%Y')%>, com carga horária de <%=@event.workload%> hora(s).</h3>

app/views/certificates/index.html.erb
<h1>Digite seu email para pesquisar seus certificados</h1>
<%=form_tag search_events_path, method: :get, class: "form-horizontal" do%>
  <div class="form-group col-md-12">
    <%=text_field_tag :email, "", class: "form-control input-lg", placeholder: "Digite seu email"%>
  </div>
  <button type="submit" class="btn btn-primary">Pesquisar</button>
<%end%>

app/views/certificates/pdf.pdf.erb
<%=wicked_pdf_image_tag "background.jpg"%>
<h3>Certificamos que <%=@participant.name%> participou como <%=@participant.participation_type%> do(a) <%=@event.name%> em <%=@event.location%>, durante o período de <%=@event.start_date.strftime('%d/%m/%Y')%> à <%=@event.end_date.strftime('%d/%m/%Y')%>, com carga horária de <%=@event.workload%> hora(s).</h3>

app/views/certificates/search.html.erb
<h1>Eventos encontrados para <%=@participant.name%></h1>
<div class="row">
  <%@events.each do |event|%>
    <div id="<%=dom_id(event)%>" class="col-md-6 event btn btn-default"><%=link_to event.name, show_certificate_path(event, @participant, format: :pdf), target: '_blank' %></div>
  <%end%>
</div>
<%=form_tag search_events_path, method: :get, class: "form-horizontal" do%>
  <div class="form-group col-md-12">
    <%=text_field_tag :email, "", class: "form-control input-lg", placeholder: "Digite seu email"%>
  </div>
  <button type="submit" class="btn btn-primary">Pesquisar novamente</button>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Certificados | Alagoas Dev Day</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12085288-8', 'auto');
  ga('send', 'pageview');

  </script>
  <div class="container">
    <div class="row">
      <div class="col-md-12 logo">
        <%=image_tag "logo.jpg" %>
      </div>
      <div class="col-md-12 content">
        <%=flash_messages%>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Certificado | <%=@participant.name%> | <%=@event.name%></title>
  <meta charset='utf-8' />
  <style>
    html, body {
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
    }
    img {
      position: absolute;
      top: 0;
      left: 0;
    }
    h3 {
      margin-top: 430px;
      margin-left: 60px;
      margin-right: 30px;
      position: relative;
    }
    .center {
      text-align: center;
    }
  </style>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= yield %>
  </body>
</html>